.PHONY: miri-test
miri-test:
	@ MIRIFLAGS="-Zmiri-tree-borrows" cargo +nightly miri test --bin design_unsafe_deque -- --nocapture



# 默认目标：显示帮助信息
.DEFAULT_GOAL := help

.PHONY: help
# 显示帮助信息
help:
	@echo ''
	@echo 'Usage:'
	@echo ' make [target]'
	@echo ''
	@echo 'Targets:'
	@awk '/^[a-zA-Z\-\_0-9]+:/ { \
		helpMessage = match(lastLine, /^# (.*)/); \
		if (helpMessage) { \
			helpCommand = substr($$1, 0, index($$1, ":")); \
			helpMessage = substr(lastLine, RSTART + 2, RLENGTH); \
			printf "\033[36m%-22s\033[0m %s\n", helpCommand, helpMessage; \
		} \
	} \
	{ lastLine = $$0 }' $(MAKEFILE_LIST)